name: Test Workflow by Bjarte

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo Job 1
        run: echo "This is the first job"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo Job 2
        run: echo "This is the second job"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: ./.github/workflows/test.sh
