name: Test Workflow by Bjarte

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_forrest:
        description: 'Run job4'
        required: false
        default: 'false'
      input1:
        description: 'First input'
        required: false
        default: ''        

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo Job 1
        run: echo "This is the first job"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo Job 2
        run: echo "This is the second job"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: ./.github/workflows/test.sh

  # Runs reusable workflow from global-workflows with test-path as input. Will also provide output, see job4      
  job-call-global-workflow:
    needs: job1
    uses: bjartekh/global-workflows/.github/workflows/global-workflow.yml@main
    with:
      test-path: .github/this-is-a-test.yml

  # Will echo the output received from reusable workflow "job-call-global-workflow"
  # Then uploads files from /dist folder 
  job-upload-artefact:
    runs-on: ubuntu-latest
    needs: job-call-global-workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Output from global
        run: echo ${{ needs.job-call-global-workflow.outputs.firstword }}
      - name: Archive artefacts 
        uses: actions/upload-artifact@v4  
        with:
          name: dist-file
          path: |
            dist
            !dist/**/*.md
          retention-days: 5

  webhook_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_forrest == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: |
          echo "run_forrest: ${{ github.event.inputs.run_forrest }}"
          echo "Input1: ${{ github.event.inputs.input1 }}"
          