name: Test Workflow by Bjarte

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_forrest:
        description: 'Run job4'
        required: false
        default: 'false'
      input1:
        description: 'First input'
        required: false
        default: ''        

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo Job 1
        run: echo "This is the first job"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo Job 2
        run: echo "This is the second job"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: ./.github/workflows/test.sh

  job-call-global-workflow:
    needs: job1
    uses: bjartekh/global-workflows/.github/workflows/global-workflow.yml@main
    with:
      test-path: .github/this-is-a-test.yml
      
    
      


  webhook_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_forrest == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: |
          echo "run_forrest: ${{ github.event.inputs.run_forrest }}"
          echo "Input1: ${{ github.event.inputs.input1 }}"
          